name: CI

on:
  pull_request:

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Install Requirements
        run: pip install -r requirements-dev.txt

      # This is needed to test the CLI entrypoint
      - name: Install zet-cli
        run: python3 -m pip install -e .

      - name: Git config for tests
        run: |
          git config --global user.name "test"
          git config --global user.email "test@zet-cli.test"

      - name: Run Pre-Commit
        run: pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install Requirements
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -vv -s

