# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort black flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Run isort checking
      run: |
        # run isort with black profile
        isort . --profile black
    - name: Run black
      run: |
        # run black
        black .
    - name: Lint with flake8
      run: |
        # exit-zero treats all errors as warnings.
        flake8 . --max-line-length=120 --ignore=E501,I001,I005
    - name: Test with pytest
      run: |
        pytest
