name: Release Zet-CLI

on:
  push:
    branches: ["master", "main"]
    tags:
      - '*'

jobs:

  release:
    name: Release build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Tag and release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    name: PyPI - Build and publish Python distributions
    runs-on: ubuntu-latest
    needs: [release]
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

